mysql:
  image: mysql
  expose:
    - "3306"
  volumes:
    - ./data:/var/lib/mysql
  env_file:
    - ./secrets.env
mediawiki:
  build: ./mediawiki
  volumes:
    - ./shared/LocalSettings.php:/var/www/html/LocalSettings.php
  links:
    - mysql
  ports:
    - 8080:80
